datasets:
  germeval2018:
    labeled-dataset: germeval2018
    unlabeled-dataset:
    non-hate-label:
  germeval2019:
    labeled-dataset: germeval2019
    unlabeled-dataset:
    non-hate-label: none
  hasoc2018:
    labeled-dataset: hasoc2018
    unlabeled-dataset:
    non-hate-label: none
  hasoc2019:
    labeled-dataset: hasoc2019
    unlabeled-dataset:
    non-hate-label: none
  telegram:
    labeled-dataset: telegram_labeled
    unlabeled-dataset: telegram_unlabeled
    non-hate-label: none 
models:
  single-source unsupervised:
    - ADDA
  single-source semi-supervised:
    - MME
  multi-source unsupervised:
    - DCTN
