datasets:
  germeval2018:
    unlabeled-dataset: False
    non-hate-label: HOF
  germeval2019:
    unlabeled-dataset: False
    non-hate-label: none
  hasoc2018:
    unlabeled-dataset: False
    non-hate-label: none
  hasoc2019:
    unlabeled-dataset: False
    non-hate-label: none
  telegram:
    unlabeled-dataset: True
    non-hate-label: none 
models:
  single-source unsupervised:
    - ADDA
  single-source semi-supervised:
    - MME
  multi-source unsupervised:
    - DCTN
